<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{53e436ba-9af9-4ca4-ad7b-a6b2399fa417}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

	fbLogHandler : FB_LogHandler;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbLogHandler();

// ADS interface PRG
PRG_ADS_Interfaces();

(* FEE devices*)
PRG_FEE();
PMPS();
PRG_FSV_Interfaces();

(*Hutch*)
PRG_Hutch_Gauges();
PRG_Hutch_Beamline_Valves();
PRG_Roughing_Pumps();








]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="3" Count="8" />
      <LineId Id="37" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="28" Count="2" />
      <LineId Id="27" Count="0" />
      <LineId Id="12" Count="6" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>