<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="PRG_Section_2" Id="{aa241f3d-e544-47fe-9c03-27baee63cd5a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Section_2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_Section_2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>